stages:
    - analysis
    - test

isort:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

test:
    image: cznic/ubuntu_python_runner:latest
    stage: test
    script:
        - pip install --find-links=/usr/share/python-wheels -r requirements.txt
        - pip list
        - make test
